# +-------------------------------------------------------------------+
# | (C) Copyright IBM Corp. 2025, 2026                                |
# | SPDX-License-Identifier: Apache-2.0                               |
# +-------------------------------------------------------------------+

name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions: read-all

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pre-commit
      uses: pre-commit/action@v3.0.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy pytest
        python -m pip install -r requirements.txt
    - name: Run local test
      run: make python-test test
